### ISSUE TITLE
The plugin doesn't work for VS2022 anymore

### ISSUE THREAD

**Issue by syby119** [fingeg/DoxygenComments#19]
In VS2022 Comunity/Professional, when I want to add a doxygen style comment to a function, the plugin doesn't work. My colleagues also encountered with the same issue. Do you have a plan to fix this problem?

**Comment by syby119** [comment]
By the way, we use the plugin for C++ project

**Comment by theRTC204** [comment]
Likewise - just found the plugin, and getting an error when attempting to view the Doxygen section in Tools > Options

The following is taken from the ActivityLog.xml file
```
SetSite failed for package [DoxygenCommentsPackage]
Source: 'Microsoft.VisualStudio.Editor.Implementation'
Description: Value cannot be null.
Parameter name: viewAdapter
System.ArgumentNullException: Value cannot be null.
Parameter name: viewAdapter
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetWpfTextViewHostFromVsTextView(IVsTextView viewAdapter)
   at Microsoft.VisualStudio.Editor.Implementation.VsEditorAdaptersFactoryService.GetWpfTextView(IVsTextView viewAdapter)
   at DoxygenComments.UpdateDoxygenCommentCmd.<InitializeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DoxygenComments.DoxygenCommentsPackage.<InitializeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```

**Comment by aljangtze** [comment]
**me to**, still can't work  correctly  in vs2022,  version 2.0.5

**Comment by redgis** [comment]
@syby119 I think if would help if you would say a bit more then "it doesn't work".

I have an issue too, where the plugin shoots the following error when I type "enter" in a `/** */` comment to trigger auto formatting : `The operation could not be completed. Unspecified error`

![Image](https://github.com/user-attachments/assets/91a10d69-9590-46eb-a5fe-d1d36ac3e737)

![Image](https://github.com/user-attachments/assets/88c754cb-ff85-4654-8ea9-e4923c3cb94b)

Is this the same error you encountered ?
